FROM maven:3.9.6 as build

WORKDIR project

COPY . /project

RUN mvn clean install

FROM openjdk:21

ENV SERVICE_NOTIFICATION_EXIT="false"

COPY --from=build /project/target/*.jar application.jar

EXPOSE 8085

CMD ["java", "-jar", "application.jar"]
