FROM ghcr.io/graalvm/native-image-community:21

RUN curl -LJ -o /opt/apache-maven.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz

RUN tar -xzf /opt/apache-maven.tar.gz -C /opt/
RUN rm -rf /opt/apache-maven.tar.gz

ENV M2_HOME /opt/apache-maven-3.9.6
ENV PATH="$PATH:$M2_HOME/bin"

WORKDIR project-maven

COPY src /project-maven/src
COPY pom.xml /project-maven/pom.xml

RUN mvn -Pnative native:compile -f /project-maven

FROM ubuntu:22.04

COPY --from=0 /project-maven/target/notification-svc notification-svc

EXPOSE 8085

CMD ["./notification-svc"]
