FROM ghcr.io/graalvm/native-image-community:21 as build

RUN curl -LJ -o /opt/apache-maven.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz && \
    tar -xzf /opt/apache-maven.tar.gz -C /opt/

WORKDIR project-maven

COPY src /project-maven/src

COPY pom.xml /project-maven/pom.xml

RUN /opt/apache-maven-3.9.6/bin/mvn -Pnative native:compile -f /project-maven

FROM alpine:3.19 as compress

COPY --from=build /project-maven/target/notification-svc native-image-svc

RUN apk add upx

RUN upx --lzma --best native-image-svc -o native-image-svc.upx

FROM ubuntu:22.04

COPY --from=compress native-image-svc.upx native-image-svc.upx

EXPOSE 8085

CMD ["./native-image-svc.upx"]
